---
title: "TP"
author: "Vincent RIBOT"
date: "12/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Simple regression
```{r}
myData=read.table(file="arbres-tot.csv", sep=";", skip=3, header=TRUE)
myData=myData[myData$X10!=0,]

circ=myData$X70
height=myData$X10
#ggplot(myData, aes(x=circ, y=height)) + geom_point() +xlab("circ") + ylab("height")
simple_reg = lm(height~circ, data=myData)
anova(simple_reg)
summary(simple_reg)
ggplot(myData, aes(x=circ, y=height)) + geom_point() + stat_smooth(method = "lm", se=FALSE) + xlab("circ") + ylab("height")
acf(residuals(simple_reg))
plot(simple_reg,2)
plot(simple_reg$residuals)
plot(simple_reg,3)
plot(simple_reg,1)
plot(simple_reg,4)
#predict(simple_reg data.frame(circ=10), interval="prediction")

```
# Multivariante regression

```{r}
myData$circ_sqrt <- sqrt(myData$X70)
multi_reg <- lm(height~circ+circ_sqrt, data=myData)
summary(multi_reg)
multi_reg2 <- lm(height~circ_sqrt, data=myData)
summary(multi_reg2)

circ_pred <- seq(0,175,len=1000)
height_pred <- multi_reg2$coeficients[1]+multi_reg2$coefficients[2]*sqrt(circ_pred)
fct_reg <-data.frame(circ_pred=circ_pred, height_pred=height_pred)
ggplot()+
  geom_point(data=myData, aes(x=circ, y=height))+
  geom_line(data=fct_reg, aes(x=circ_pred, y=height_pred, col="blue"))+
  stat_smooth(method="lm", se=FALSE)+
  xlab("circ")+
  ylab("height")
```

